### ISSUE TITLE
System.ArgumentException: Cannot be less than 2. (Parameter 'maxItemCount')

### ISSUE THREAD

**Issue by marcinkopij** [tylerjensen/FuzzyStrings#10]
Hello

# Problem
When I host my app using FuzzyStrings in OCP (OpenShift Container Platfrom) I receive an error during FuzzySearch.FuzzyEquals execution:

```
System.ArgumentException: Cannot be less than 2. (Parameter 'maxItemCount')
   at Ruzzie.Common.Caching.FlashCache`2..ctor(IEqualityComparer`1 comparer, Int32 maxItemCount)
   at Ruzzie.FuzzyStrings.StringExtensions..cctor()
```
# Reason
The reason is that in InternalVariables class MaxCacheSizeInMb is being calculated based on Process.MaxWorkingSet property:
```c#
using (Process currentProcess = Process.GetCurrentProcess())
{
    bytesOfMemoryAvailable = currentProcess.MaxWorkingSet.ToInt64() * 16;
}

mbOfMemoryAvailable = (int)((bytesOfMemoryAvailable / 1024) / 1024)
```
In case of OCP pod this value returns 2147483648 which is 2048 Megabytes. 
It actually returns 4096 as Property but .NET shows it as max int value which is 2147483648 

# BUG location
The bug is in StringExtensions class.

In:

```c#
private static readonly FlashCache<string, double> Cache =
    new FlashCache<string, double>(InternalVariables.StringComparerForCacheKey, (InternalVariables.MaxCacheSizeInMb * 1024 * 1024) / InternalVariables.AverageStringSizeInBytes);
```

# Solution
## Quick (dirty)
Instead of:
```c#
 InternalVariables.MaxCacheSizeInMb * 1024 * 1024)
``` 
 it should be 
```c#
(double)InternalVariables.MaxCacheSizeInMb * 1024 * 1024)
```

So the final code of 
instead of  this:
```c#
public static class StringExtensions
{
    private static readonly FlashCache<string, double> Cache =
        new FlashCache<string, double>(InternalVariables.StringComparerForCacheKey, InternalVariables.MaxCacheSizeInMb * 1024 * 1024) / InternalVariables.AverageStringSizeInBytes);
```
should be:
```c#
public static class StringExtensions
{
    private static readonly FlashCache<string, double> Cache =
        new FlashCache<string, double>(InternalVariables.StringComparerForCacheKey, ((double)InternalVariables.MaxCacheSizeInMb * 1024 * 1024) / InternalVariables.AverageStringSizeInBytes);
```

## Longer (clean solution) - requires also changes in Ruzzie.Common.Caching.FlashCache

Change types in InternalVariables class
From:
```c#
using System;
using System.Diagnostics;
using Ruzzie.Common.Caching;

namespace Ruzzie.FuzzyStrings
{
    public static class InternalVariables
    {
        public static readonly int DefaultCacheItemSizeInMb;
        public static readonly int AverageStringSizeInBytes = 284;
        public static readonly int MaxCacheSizeInMb;

        public static readonly StringComparerOrdinalIgnoreCaseFNV1AHash StringComparerForCacheKey =
            new StringComparerOrdinalIgnoreCaseFNV1AHash();

        static InternalVariables()
        {
            int mbOfMemoryAvailable = 0;
            try
            {
                long bytesOfMemoryAvailable;

                using (Process currentProcess = Process.GetCurrentProcess())
                {
                    bytesOfMemoryAvailable = currentProcess.MaxWorkingSet.ToInt64() * 16;
                }

                mbOfMemoryAvailable = (int)((bytesOfMemoryAvailable / 1024) / 1024);
            }
            finally
            {
                DefaultCacheItemSizeInMb = Math.Max(1, mbOfMemoryAvailable   / 400);
                MaxCacheSizeInMb         = Math.Max(DefaultCacheItemSizeInMb * 2, mbOfMemoryAvailable / 8);
            }
        }
    }
}
```

To:
```c#
using System;
using System.Diagnostics;
using Ruzzie.Common.Caching;

namespace Ruzzie.FuzzyStrings
{
    public static class InternalVariables
    {
        public static readonly double DefaultCacheItemSizeInMb;
        public static readonly int AverageStringSizeInBytes = 284;
        public static readonly double MaxCacheSizeInMb;

        public static readonly StringComparerOrdinalIgnoreCaseFNV1AHash StringComparerForCacheKey =
            new StringComparerOrdinalIgnoreCaseFNV1AHash();

        static InternalVariables()
        {
            double mbOfMemoryAvailable = 0;
            try
            {
                double bytesOfMemoryAvailable;

                using (Process currentProcess = Process.GetCurrentProcess())
                {
                    bytesOfMemoryAvailable = currentProcess.MaxWorkingSet.ToInt64() * 16;
                }

                mbOfMemoryAvailable =bytesOfMemoryAvailable / 1024 / 1024;
            }
            finally
            {
                DefaultCacheItemSizeInMb = Math.Max(1, mbOfMemoryAvailable   / 400);
                MaxCacheSizeInMb         = Math.Max(DefaultCacheItemSizeInMb * 2, mbOfMemoryAvailable / 8);
            }
        }
    }
}
```
Otherwsie when the limit is set very high (like in my case) whole calculation returns 0 (due to int overflow) which is lower than 2 and then ArgumentException is thrown.

# EASY WAY TO REPRDUCE THE ISSUE:
👎 Wrong (int overflow) - returns 0:
```c#
using System.Diagnostics;

int maxCacheSizeInMb = 4096; //THIS IS what InternalVariables.MaxCacheSizeInMb property returns - it's INT
int averageStringSizeInBytes = 284;

double result = maxCacheSizeInMb * 1024 * 1024 / averageStringSizeInBytes;

Console.WriteLine($"Result: {result}");

Console.ReadKey();

```
👍  Correct :
```c#
using System.Diagnostics;

int maxCacheSizeInMb = 4096; //THIS IS what InternalVariables.MaxCacheSizeInMb property returns - it's INT
int averageStringSizeInBytes = 284;

double result = (double)maxCacheSizeInMb * 1024 * 1024 / averageStringSizeInBytes;

Console.WriteLine($"Result: {result}");

Console.ReadKey();

```

**Comment by Ruzzie** [comment]
What an extensive and awesome bug report! Thank you! 

I fixed this in the https://github.com/Ruzzie/fuzzystrings repository where this code resides. 
This repo is the original where I forked from.

Be aware that I forked and optimized my fork of the FuzzyStrings library for pretty niche use cases, that is why the cache is in there. I'm happy to see it also works for you :)

**Comment by marcinkopij** [comment]
Thanks a lot for turbo fix!
I've tested in OCP with the newest version [7.0.1.58](https://www.nuget.org/packages/Ruzzie.FuzzyStrings/7.0.1.58)
and it works fine.

The solution (fuzzystrings) is really cool and it makes a job in my project 🥇 .

Happy that I could help.
One more time - thanks a lot.
